version: '3.8'
services:
  builder_api:
    image: bsa2020builder/builder_api:latest
    container_name: 'builder_api'
    restart: on-failure
    ports:
        - "5050:5050"
    environment:
        ASPNETCORE_ENVIRONMENT: 'Production'
    
  builder_processor:
      image: bsa2020builder/builder_processor:latest
      container_name: 'builder_processor'
      restart: on-failure
      ports:
          - "5060:5060"
      environment:
          ASPNETCORE_ENVIRONMENT: 'Production'

  builder_signalr:
      image: bsa2020builder/builder_signalr:latest
      container_name: 'builder_signalr'
      restart: on-failure
      ports:
          - "5070:5070"
      environment:
          ASPNETCORE_ENVIRONMENT: 'Production'

  builder_frontend:
    depends_on:
        - builder_api
        - builder_processor
        - builder_signalr
    image: bsa2020builder/builder_frontend:latest
    container_name: 'builder_frontend'
    restart: on-failure
    ports:
        - "80:80"
        - "443:443"
    volumes:
       - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
       - /etc/nginx/dhparam.pem:/etc/nginx/dhparam.pem
       - /etc/nginx/sites-available:/etc/nginx/sites-available
       - /etc/nginx/nginxconfig.io:/etc/nginx/nginxconfig.io
       - /etc/letsencrypt:/etc/letsencrypt
       - /var/log/nginx:/var/log/nginx