version: '3.8'
services: 
    vault:
        image: vault:1.5.0
        container_name: vault
        restart: on-failure
        ports:
            - 8200:8200
        networks:
            - back
        environment: 
            - VAULT_DEV_ROOT_TOKEN_ID='buildeR_DEV_TOKEN'
        cap_add:
            - IPC_LOCK

    rabbitmq:
        image: rabbitmq:3.8.6-management
        container_name: rabbitmq
        restart: on-failure
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - back
        environment:
            - "RABBITMQ_DEFAULT_USER=guest"
            - "RABBITMQ_DEFAULT_PASS=guest"

    elasticsearch:
        image: elasticsearch:7.8.1
        container_name: elasticsearch
        ports:
            - 9200:9200
        networks:
            - back
        environment:
            - xpack.monitoring.enabled=true
            - xpack.watcher.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - discovery.type=single-node

    kibana:
        depends_on:
            - elasticsearch
        image: kibana:7.8.1
        container_name: kibana
        ports:
            - 5601:5601
        networks:
            - back
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200
    
    zookeeper:
        image: confluentinc/cp-zookeeper:5.5.1
        ports:
            - 2181:2181
            - 2000:2000
        networks:
            - back
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
    
    kafka:
        image: confluentinc/cp-kafka:5.5.1
        depends_on:
            - zookeeper
        ports:
            - 9092:9092
        networks:
            - back
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    sql_server:
        image: mcr.microsoft.com/mssql/server:2017-latest
        container_name: sql_server
        ports:
            - 1433:1433
        networks:
            - back
        environment:
            SA_PASSWORD: MySecretPassword!
            ACCEPT_EULA: "Y"

networks:
    back:
        driver: bridge