name: Build SRC

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Build .NET
      run: dotnet build backend/buildeR.sln --configuration Release

    - name: Slack notification
    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: message,commit,author,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: failure()

  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 12.x
      - name: Install packages and build Angular
        run: |
          cd frontend
          npm ci
          npx ng build --prod

      - name: Slack notification
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: message,commit,author,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()
        
